### PR TITLE
Add Intro Section Logos

### PR DESCRIPTION
**Pull request by maennchen**
image

## TODO

* [x] Check Trademark Policy with Erlang - @IngelaAndin 
* [x] Check Trademark Policy with Elixir - @josevalim
* [x] Check Trademark Policy with Gleam - @lpil
* [x] Check Trademark Policy with Hex.pm - @wojtekmach

### CODE REVIEW

**Comment by josevalim** [comment]
All good from me. Elixir trademark allows nominative use and, if you have reservations, this comment can be used as permission.

**Comment by lpil** [comment]
All good for Gleam! Thank you Jonatan.

**Comment by IngelaAndin** [comment]
I think it looks good, will double check with my boss to make totally sure.

**Review by wojtekmach — APPROVED** [review]
All good from Hex side, thanks!

**Pull request merged**
